version: '3.8'
services:
  java-maven-app:
    image: aitvaras/demo-app:jma-1.0
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    port:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd